### ISSUE TITLE
Error when adding a new component

### ISSUE THREAD

**Issue by transistorfet** [mggates39/ChipInventory#14]
I started docker compose, and after navigating to the `/import/all` link to import the components, I can see the chipdb components in the list, but when I go to create a new component, I get a template error shown below.

The input values I used where:
```
Component Number: 74HC32
Aliases: <blank>
Description: Quad 2-input OR gate
Type: 7400
Package: SOP
Pin Count: 14
Family: 7400
Datasheet: <blank>
```

I would have expected it would either give an error that a field was invalid, or else that the component would be added to the database, and appear in the list of components.

```
/home/node/app/views/component/new.pug:39 37| - while (n < data.pin_count) 38| div.row.mb-3 > 39| input(type="hidden" id="pin_id_"+n name="pin_id_"+n value=data.pin_id[n]) 40| div.col-sm-2 41| input.form-control(type="text" id="pin_"+n name="pin_"+n value=(n+1)) 42| div.col-sm-2 Cannot read properties of undefined (reading '0')

TypeError: /home/node/app/views/component/new.pug:39
    37|     - while (n < data.pin_count)
    38|       div.row.mb-3 
  > 39|         input(type="hidden" id="pin_id_"+n name="pin_id_"+n value=data.pin_id[n])
    40|         div.col-sm-2 
    41|           input.form-control(type="text" id="pin_"+n name="pin_"+n value=(n+1))
    42|         div.col-sm-2 

Cannot read properties of undefined (reading '0')
    at eval (eval at wrap (/home/node/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:291:170)
    at template (eval at wrap (/home/node/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:342:7)
    at exports.renderFile (/home/node/app/node_modules/pug/lib/index.js:454:38)
    at exports.renderFile (/home/node/app/node_modules/pug/lib/index.js:444:21)
    at exports.__express [as engine] (/home/node/app/node_modules/pug/lib/index.js:493:11)
    at View.render (/home/node/app/node_modules/express/lib/view.js:139:8)
    at tryRender (/home/node/app/node_modules/express/lib/application.js:643:10)
    at Function.render (/home/node/app/node_modules/express/lib/application.js:595:3)
    at ServerResponse.render (/home/node/app/node_modules/express/lib/response.js:911:7)
    at /home/node/app/routes/chips.js:116:9
```

**Comment by mggates39** [comment]
You found a latent bug in the last form refactoring.  I will have a fix for it shortlly.
